parameters:
 - name: exec_environment
   displayName: "Execution Environment"
   default: "dev"
 - name: flow_to_execute
   displayName: "type of model to execute"
 - name: deployment_type
   displayName: "determine managed or kubernetes deployment"

stages:
    - stage: execute_prompt_experiment
      jobs:
      - job: Execute_ml_Job_Pipeline
        steps:
        - ${{ if eq(parameters.deployment_type, 'aml') }}:
          - script: |
              echo "aml"
            displayName: 'aml run'


        - ${{ if eq(parameters.deployment_type, 'kubernetes') }}:
          - script: |
              echo "kubernetes"
            displayName: 'kubernetes run'