name: platform_cd_dev_workflow

on:
  workflow_call:
    inputs:
      env_name:
        type: string
        description: "Execution Environment"
        required: true
      flow_type:
        type: string
        description: "The flow use-case to execute"
        required: true
      deployment_type:
        type: string
        description: "Determine managed(False) or kubernetes(True) deployment"
        required: true
    secrets:
      azure_credentials:
        description: "service principal auth to Azure"
        required: true
  workflow_dispatch:
    inputs:
      env_name:
        type: string
        description: "Execution Environment"
        required: true
        default: "dev"
      flow_type:
        type: string
        description: "The flow use-case to execute"
        required: true
      deployment_type:
        type: string
        description: "Determine managed(False) or kubernetes(True) deployment"
        required: true

jobs:
  flow-deployment:
    name: prompt flow deployment job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
      #=====================================
      # Executed Kubernetes deployment when parameter IS_KUBERNETES_DEPLOYMENT == 'True'

      #=====================================             
      - name: Deploy to AML real-time online endpoint
        if: ${{ github.event.inputs.deployment_type == 'aml'  }} 
        id: subscription_details
        shell: bash
        run: |
          echo "aml"

      #=====================================
      # Executed AML Compute deployment when parameter IS_KUBERNETES_DEPLOYMENT == 'False'
      # Reads 'azure_managed_endpoint' field values from deployment_config.json
      #=====================================     
      - name: Deploy to kubernetes real-time online endpoint
        if: ${{ github.event.inputs.deployment_type == 'kubernetes'  }}  
        id: subscription_details1
        shell: bash
        run: |
          echo "kubernetes"


        
            





            
